name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
  
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup msbuild.exe
      uses: microsoft/setup-msbuild@v1.0.0
      
    - name: static analysis of patient-monitor
      run: ./Cppcheck_Config/cppcheck.exe --project=".\devices\patient-monitors\patient-monitors.vcxproj" --suppress=unusedFunction --verbose --std=c++11 --language=c++ --enable=all --error-exitcode=1

    - name: static analysis of ultra-sound
      run: ./Cppcheck_Config/cppcheck.exe --project=".\devices\ultra-sound\ultra-sound.vcxproj" --suppress=unusedFunction --verbose --std=c++11 --language=c++ --enable=all --error-exitcode=1

    - name: static analysis of x-ray
      run: ./Cppcheck_Config/cppcheck.exe --project=".\devices\x-ray\x-ray.vcxproj" --suppress=unusedFunction --verbose --std=c++11 --language=c++ --enable=all --error-exitcode=1
    
    - name: Build patient-monitors
      run: msbuild devices/patient-monitors/patient-monitors.vcxproj /p:configuration=debug /p:platform=x64 
    
    - name: Build ultra-sound
      run: msbuild devices/ultra-sound/ultra-sound.vcxproj /p:configuration=debug /p:platform=x64
    
    - name: Build x-ray
      run: msbuild devices/x-ray/x-ray.vcxproj /p:configuration=debug /p:platform=x64
   
    - name: Cleaning patient-monitors build folder
      run: msbuild devices/patient-monitors/patient-monitors.vcxproj /t:clean /p:configuration=debug /p:platform=x64
      
    - name: Cleaning ultra-sound build folder
      run: msbuild devices/ultra-sound/ultra-sound.vcxproj /t:clean /p:configuration=debug /p:platform=x64
    
    - name: Cleaning x-ray build folder
      run: msbuild devices/x-ray/x-ray.vcxproj /t:clean /p:configuration=debug /p:platform=x64

    - name: Build patient-monitors-test
      run: msbuild devices/patient-monitors-test/patient-monitors-test.vcxproj /p:configuration=debug /p:platform=x64
    
    - name: Build ultra-sound-test
      run: msbuild devices/ultra-sound-test/ultra-sound-test.vcxproj /p:configuration=debug /p:platform=x64
    
    - name: Build x-ray-test
      run: msbuild devices/x-ray-test/x-ray-test.vcxproj /p:configuration=debug /p:platform=x64

    - name: Run patient-monitors-test
      run: ./devices/patient-monitors-test/x64/debug/patient-monitors-test.exe   

    - name: Run patient-monitors-test
      run: ./devices/ultra-sound-test/x64/debug/ultra-sound-test.exe   

    - name: Run patient-monitors-test
      run: ./devices/x-ray-test/x64/debug/x-ray-test.exe   